[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "v0.0.7"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "v1.13.7"

[[constraint]]
  name = "github.com/pavel-v-chernykh/keystore-go"
  version = "v2.1.0"
