console:
  deploymentConfigs:
    - metadata:
        name: "{{.ApplicationName}}-rhpamcentr"
      spec:
        template:
          metadata:
            name: "{{.ApplicationName}}-rhpamcentr"
          spec:
            containers:
              - name: "{{.ApplicationName}}-rhpamcentr"
                ports:
                  - name: git-ssh
                    containerPort: 8001
                    protocol: TCP
                volumeMounts:
                  - name: "{{.ApplicationName}}-rhpamcentr-pvol"
                    mountPath: "/opt/eap/standalone/data/kie"
                resources:
                  limits:
                    memory: 2Gi
            volumes:
              - name: "{{.ApplicationName}}-rhpamcentr-pvol"
                persistentVolumeClaim:
                  claimName: "{{.ApplicationName}}-rhpamcentr-claim"
  services:
    - spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
      metadata:
        name: "{{.ApplicationName}}-rhpamcentr"

## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #{{ range $index, $Map := .ServerCount }}
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          replicas: 1
          template:
            metadata:
              name: "{{.ApplicationName}}-kieserver-{{$index}}"
            spec:
              containers:
                - name: "{{.ApplicationName}}-kieserver-{{$index}}"
                  env:
                    - name: MAVEN_REPOS
                      value: "RHPAMCENTR,EXTERNAL"
                    - name: KIE_SERVER_CONTROLLER_TOKEN
                      value: ""
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_DATABASE
                      value: "rhpam7"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_JTA
                      value: "true"
                    - name: KIE_SERVER_PERSISTENCE_DS
                      value: "java:/jboss/datasources/rhpam"
                    ## H2 driver settings BEGIN
                    - name: RHPAM_DRIVER
                      value: "h2"
                    - name: RHPAM_USERNAME
                      value: "sa"
                    - name: RHPAM_PASSWORD
                      value: "{{.AdminPassword}}"
                    - name: RHPAM_SERVICE_HOST
                      value: "dummy_ignored"
                    - name: RHPAM_SERVICE_PORT
                      value: "12345"
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "org.hibernate.dialect.H2Dialect"
                    - name: DROOLS_SERVER_FILTER_CLASSES
                      value: "true"
                    - name: RHPAM_XA_CONNECTION_PROPERTY_URL
                      value: "jdbc:h2:/opt/eap/standalone/data/rhpam"
                  ## H2 driver settings END
                  volumeMounts:
                    - name: "{{.ApplicationName}}-h2-pvol"
                      mountPath: "/opt/eap/standalone/data"
              volumes:
                ## H2 volume settings BEGIN
                - name: "{{.ApplicationName}}-h2-pvol"
                  persistentVolumeClaim:
                    claimName: "{{.ApplicationName}}-h2-claim-{{$index}}"
    ## KIE server deployment config END
    persistentVolumeClaims:
      ## H2 persistent volume claim BEGIN
      - metadata:
          name: "{{.ApplicationName}}-h2-claim-{{$index}}"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Gi"
      ## H2 persistent volume claim END
#{{end}}
## RANGE ends
## KIE Servers END
