## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #{{ range $index, $Map := .ServerCount }}
  ## KIE server build config BEGIN
  - imageStreams:
      - metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-kieserver-{{$index}}"
    buildConfigs:
      - metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          source:
            type: Git
            git:
              uri: "{{.GitSource.URI}}"
              ref: "{{.GitSource.Reference}}"
            contextDir: "{{.GitSource.ContextDir}}"
          strategy:
            type: Source
            sourceStrategy:
              env:
                - name: KIE_SERVER_CONTAINER_DEPLOYMENT
                  value: "{{.KieServerContainerDeployment}}"
              forcePull: true
              from:
                kind: ImageStreamTag
                namespace: "openshift"
                name: "{{.Product}}{{.Version}}-kieserver-openshift:{{.ImageTag}}"
          output:
            to:
              kind: ImageStreamTag
              name: "{{.ApplicationName}}-kieserver-{{$index}}:latest"
          triggers:
            - type: GitHub
              github:
                secret: "{{.GitHubWebhookSecret}}"
            - type: Generic
              generic:
                secret: "{{.GenericWebhookSecret}}"
            - type: ImageChange
              imageChange: {}
            - type: ConfigChange
    ## KIE server build config END
    ## KIE server deployment config BEGIN
    deploymentConfigs:
      - metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          replicas: 2
          triggers:
            - type: ImageChange
              imageChangeParams:
                automatic: true
                containerNames:
                  - "{{.ApplicationName}}-kieserver-{{$index}}"
                from:
                  kind: ImageStreamTag
                  namespace: ""
                  name: "{{.ApplicationName}}-kieserver-{{$index}}:latest"
          template:
            spec:
              containers:
                - name: "{{.ApplicationName}}-kieserver-{{$index}}"
                  image: "{{.ApplicationName}}-kieserver-{{$index}}"
      ## KIE server deployment config END
#{{end}}
## RANGE ends
## KIE Servers END
