console:
  deploymentConfigs:
    - metadata:
        name: "{{.ApplicationName}}-rhpamcentr"
      spec:
        template:
          metadata:
            name: "{{.ApplicationName}}-rhpamcentr"
          spec:
            containers:
              - name: "{{.ApplicationName}}-rhpamcentr"
                ports:
                  - name: git-ssh
                    containerPort: 8001
                    protocol: TCP
                env:
                  - name: KIE_ADMIN_PWD
                    value: RedHat
                  - name: KIE_MAVEN_PWD
                    value: RedHat
                  - name: KIE_SERVER_CONTROLLER_PWD
                    value: RedHat
                  - name: KIE_SERVER_PWD
                    value: RedHat
                resources:
                  limits:
                    memory: 2Gi
  services:
    - spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
      metadata:
        name: "{{.ApplicationName}}-rhpamcentr"
  routes:
    - id: "{{.ApplicationName}}-rhpamcentr-http"
      metadata:
        name: "{{.ApplicationName}}-rhpamcentr-http"
        labels:
          app: "{{.ApplicationName}}"
          service: "{{.ApplicationName}}-rhpamcentr"
        annotations:
          description: Route for Business Central's http service.
          haproxy.router.openshift.io/timeout: 60s
      spec:
        host: ""
        to:
          name: "{{.ApplicationName}}-rhpamcentr"
        port:
          targetPort: http
  persistentVolumeClaims:
    - metadata:
        name: "{{.ApplicationName}}-rhpamcentr-claim"
        annotations:
          delete: "true"

## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  {{ range $index, $Map := .ServerCount }}
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          replicas: 1
          template:
            metadata:
              name: "{{.ApplicationName}}-kieserver-{{$index}}"
            spec:
              containers:
                - name: "{{.ApplicationName}}-kieserver"
                  env:
                    - name: MAVEN_REPOS
                      value: "RHPAMCENTR,EXTERNAL"
                    - name: RHPAMCENTR_MAVEN_REPO_USERNAME
                      value: mavenUser
                    - name: RHPAMCENTR_MAVEN_REPO_PASSWORD
                      value: "{{.MavenPassword}}"
                    - name: RHPAMCENTR_MAVEN_REPO_PATH
                      value: /maven2/
                    - name: RHPAMCENTR_MAVEN_REPO_SERVICE
                      value: "{{.ApplicationName}}-rhpamcentr"
                    - name: KIE_SERVER_CONTROLLER_TOKEN
                      value: ""
                    - name: KIE_SERVER_ID
                      value: "{{.ApplicationName}}-kieserver-{{$index}}"
                    - name: KIE_SERVER_ROUTE_NAME
                      value: "{{.ApplicationName}}-kieserver-{{$index}}"
                    - name: KIE_SERVER_USE_SECURE_ROUTE_NAME
                      value: "false"
                    - name: KIE_ADMIN_PWD
                      value: RedHat
                    - name: KIE_SERVER_CONTROLLER_PWD
                      value: RedHat
                    - name: KIE_SERVER_PWD
                      value: RedHat
                    - name: EXECUTION_SERVER_ROUTE_NAME
                      value: "{{.ApplicationName}}-kieserver-{{$index}}"
    ## KIE server deployment config END
    persistentVolumeClaims:
      - metadata:
          name: "{{.ApplicationName}}-h2-claim-{{$index}}"
          annotations:
            delete: "true"
    {{end}}
## RANGE ends
## KIE Servers END
