apiVersion: app.kiegroup.org/v1alpha1
kind: KieApp
metadata:
  name: trial
spec:
  environment: trial
  objects:
    console:
      resources:
        limits:
          memory: 2Gi
    server:
      resources:
        requests:
          memory:
