apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: rhdm-sso
spec:
  environment: rhdm-trial
  auth:
    sso:
      url: https://rh-sso.example.com:8443
      realm: rhdm
  objects:
    console:
      ssoClient:
        name: rhdm-console
    servers:
      - name: one
        deployments: 2
        ssoClient:
          name: kieserver-one
      - name: two
        ssoClient:
          name: kieserver-two
