apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: server-common-config
spec:
  environment: rhpam-trial
  objects:
    console:
      env:
        - name: MY_VALUE
          value: "example"
    servers:
      # Kieserver sets will be named sequentially rhpam-trial-kieserver-0
      - deployments: 2
        # Env variables that will be added to all the kie servers
        env:
          - name: MY_VALUE
            value: "example"
        # Override default memory limits for all the kie servers
        resources:
          memory:
            limits: 2Gi
    smartRouter:
      env:
        - name: MY_VALUE
          value: "example"
