apiVersion: kiegroup.org/v1
kind: App
metadata:
  name: authoring
spec:
  environment: authoring
  kieDeployments: 2
  objects:
    console:
      resources:
        limits:
          memory: 2Gi
      env:
      - name: key1
        value: value1
    server:
      resources:
        limits:
          memory: 2Gi
