apiVersion: kiegroup.org/v1
kind: App
metadata:
  name: production
spec:
  environment: prod
  numKieServers: 2
  console:
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi
    env:
    - name: key1
      value: value1
    - name: key2
      value: value2
  server:
    resources:
      limits:
        memory: 2Gi
