apiVersion: kiegroup.org/v1
kind: App
metadata:
  name: trial
spec:
  environment: trial
  objects:
    console:
      resources:
        limits:
          memory: 2Gi
    server:
      resources:
        requests:
          memory:
