console:
  deploymentConfigs:
  - metadata:
      labels:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-rhpamcentr"
      name: "{{.ApplicationName}}-rhpamcentr"
    spec:
      replicas: 1
      selector:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-rhpamcentr"
      strategy:
        resources: {}
        type: Recreate
      template:
        metadata:
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-rhpamcentr"
          name: "{{.ApplicationName}}-rhpamcentr"
        spec:
          containers:
          - env:
            - name: KIE_MAVEN_USER
              value: mavenUser
            - name: KIE_MAVEN_PWD
              value: "{{.AppPassword}}"
            image: rhpam{{.Version}}-businesscentral-openshift
            imagePullPolicy: Always
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1Gi
            livenessProbe:
              exec:
                command:
                - /bin/bash
                - -c
                - curl --fail --silent -u adminUser:{{.AppPassword}} http://localhost:8080/kie-wb.jsp
              initialDelaySeconds: 180
              periodSeconds: 15
              timeoutSeconds: 2
            name: "{{.ApplicationName}}-rhpamcentr"
            ports:
            - containerPort: 8001
              name: git-ssh
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            readinessProbe:
              exec:
                command:
                - /bin/bash
                - -c
                - curl --fail --silent -u adminUser:{{.AppPassword}} http://localhost:8080/kie-wb.jsp
              failureThreshold: 6
              initialDelaySeconds: 60
              periodSeconds: 30
              timeoutSeconds: 2
          terminationGracePeriodSeconds: 60
      test: false
      triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
          - "{{.ApplicationName}}-rhpamcentr"
          from:
            kind: ImageStreamTag
            name: rhpam{{.Version}}-businesscentral-openshift:{{.ImageTag}}
            namespace: openshift
        type: ImageChange
      - type: ConfigChange
  routes:
  - metadata:
      labels:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-rhpamcentr"
      name: "{{.ApplicationName}}-rhpamcentr"
    spec:
      port:
        targetPort: http
      to:
        name: "{{.ApplicationName}}-rhpamcentr"
  services:
  - metadata:
      labels:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-rhpamcentr"
      name: "{{.ApplicationName}}-rhpamcentr"
    spec:
      ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: git-ssh
        port: 8001
        protocol: TCP
        targetPort: 8001
      selector:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-rhpamcentr"

## KIE Servers BEGIN
servers:
## RANGE BEGINS
{{ range $index, $Map := .ServerCount }}

- deploymentConfigs:
  - metadata:
      labels:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-kieserver-{{$index}}"
      name: "{{.ApplicationName}}-kieserver-{{$index}}"
    spec:
      replicas: 1
      selector:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-kieserver-{{$index}}"
      strategy:
        resources: {}
        type: Recreate
      template:
        metadata:
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-kieserver-{{$index}}"
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          containers:
          - env:
            - name: EXECUTION_SERVER_ROUTE_NAME
              value: "{{.ApplicationName}}-kieserver-{{$index}}"
            - name: RHPAMCENTR_MAVEN_REPO_USERNAME
              value: mavenUser
            - name: RHPAMCENTR_MAVEN_REPO_PASSWORD
              value: "{{.AppPassword}}"
            - name: RHPAMCENTR_MAVEN_REPO_SERVICE
              value: "{{.ApplicationName}}-rhpamcentr"
            image: rhpam{{.Version}}-kieserver-openshift
            imagePullPolicy: Always
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 1Gi
            livenessProbe:
              exec:
                command:
                - /bin/bash
                - -c
                - curl --fail --silent -u adminUser:{{.AppPassword}} http://localhost:8080/services/rest/server/healthcheck
              initialDelaySeconds: 180
              periodSeconds: 15
              timeoutSeconds: 2
            name: "{{.ApplicationName}}-kieserver-{{$index}}"
            ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            readinessProbe:
              exec:
                command:
                - /bin/bash
                - -c
                - curl --fail --silent -u adminUser:{{.AppPassword}} http://localhost:8080/services/rest/server/readycheck
              failureThreshold: 6
              initialDelaySeconds: 60
              periodSeconds: 30
              timeoutSeconds: 2
          terminationGracePeriodSeconds: 60
      test: false
      triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
          - "{{.ApplicationName}}-kieserver-{{$index}}"
          from:
            kind: ImageStreamTag
            name: rhpam{{.Version}}-kieserver-openshift:{{.ImageTag}}
            namespace: openshift
        type: ImageChange
      - type: ConfigChange
  services:
  - metadata:
      labels:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-kieserver-{{$index}}"
      name: "{{.ApplicationName}}-kieserver-{{$index}}"
    spec:
      ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-kieserver-{{$index}}"
  routes:
  - metadata:
      labels:
        app: "{{.ApplicationName}}"
        service: "{{.ApplicationName}}-kieserver-{{$index}}"
      name: "{{.ApplicationName}}-kieserver-{{$index}}"
    spec:
      port:
        targetPort: http
      to:
        name: "{{.ApplicationName}}-kieserver-{{$index}}"
{{end}}
## RANGE ends
## KIE Servers END
