apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: kiecloud-operator.v0.1.0
  namespace: placeholder
  annotations:
    categories: kieapp, rhpam, rhdm, kie, cloud, pam, bpm, process, case, automation, operator
    certified: "false"
    description: KieCloud can deploy RHPAM/RHDM environments in the form of KieApp objects.
    containerImage: quay.io/kiegroup/kie-cloud-operator:0.1
    createdAt: 2019-01-25T20:48:22Z
    support: Red Hat, Inc.
    tectonic-visibility: ocs
    alm-examples: >-
      [{"apiVersion":"app.kiegroup.org/v1","kind":"KieApp","metadata":{"name":"trial"},"spec":{"environment":"rhpam-trial"}}]
  labels:
    operator-kiecloud: "true"
spec:
  displayName: KieCloud
  description: KieCloud can deploy RHPAM/RHDM environments in the form of KieApp objects.
  keywords:
    [
      kieapp rhpam rhdm kie cloud pam bpm process case automation decision operator,
    ]
  version: 0.1.0
  maturity: beta
  maintainers:
    - name: Red Hat, Inc.
      email: bsig-cloud@redhat.com
  provider:
    name: Red Hat, Inc.
  links:
    - name: Product Page
      url: https://access.redhat.com/products/red-hat-process-automation-manager
    - name: Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.2/html-single/installing_and_configuring_red_hat_process_automation_manager_on_red_hat_jboss_eap_7.2/
  icon:
    - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMH0uY2xzLTJ7ZmlsbDojYzIxYTAwfS5jbHMtM3tmaWxsOiNjZGNkY2R9LmNscy00e2ZpbGw6I2ZmZn0uY2xzLTV7ZmlsbDojZWFlYWVhfTwvc3R5bGU+PC9kZWZzPjx0aXRsZT5Mb2dvPC90aXRsZT48ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIj48Y2lyY2xlIGNsYXNzPSJjbHMtMSIgY3g9IjUwIiBjeT0iNTAiIHI9IjUwIiB0cmFuc2Zvcm09InJvdGF0ZSgtNDUgNTAgNTApIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNODUuMzYgMTQuNjRhNTAgNTAgMCAwIDEtNzAuNzIgNzAuNzJ6Ii8+PHBhdGggY2xhc3M9ImNscy0zIiBkPSJNNTMuNTYgMjIuNzJ2MzguOWwtNi4xNyAyLjU1djEyLjI1YTI3IDI3IDAgMCAwIDIuNzMuM1Y2Ni40Nmw2LjE3LTIuNTVWMjMuMDZjLS45LS4xNi0xLjgxLS4yNy0yLjczLS4zNHoiLz48cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Ik01MS41NCAyMGEzMC4xNCAzMC4xNCAwIDAgMC00LjE1IDYwVjY0LjE3bDYuMTctMi41NVYyMC4wOWMtLjY3LS4wOS0xLjM0LS4wOS0yLjAyLS4wOXpNNDAuMzkgNTEuNTlhMi4yNiAyLjI2IDAgMSAxIDIuMjYtMi4yNiAyLjI2IDIuMjYgMCAwIDEtMi4yNiAyLjI2eiIvPjxjaXJjbGUgY3g9IjQwLjM5IiBjeT0iNDkuMzMiIHI9IjIuMjYiLz48Y2lyY2xlIGN4PSI2Mi43IiBjeT0iNDkuMzMiIHI9IjIuMjYiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik01Ni4yOSAyMy4wNnY0MC44NWwtNi4xNyAyLjU1Vjc2LjdjLjQ3IDAgLjk1LjA1IDEuNDMuMDVhMjcuMDYgMjcuMDYgMCAwIDAgNC43NC01My42OXptNi40MSAyOC41M2EyLjI2IDIuMjYgMCAxIDEgMi4zLTIuMjYgMi4yNiAyLjI2IDAgMCAxLTIuMyAyLjI2eiIvPjwvZz48L3N2Zz4=
      mediatype: image/svg+xml
  labels:
    alm-owner-kiecloud: kiecloud-operator
    operated-by: kiecloud-operator.v0.1.0
  selector:
    matchLabels:
      alm-owner-kiecloud: kiecloud-operator
      operated-by: kiecloud-operator.v0.1.0
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: true
  customresourcedefinitions:
    owned:
      - version: v1
        kind: KieApp
        description: An instance of KieApp
        displayName: KieApp
        name: kieapps.app.kiegroup.org
        resources:
          - kind: DeploymentConfig
            version: apps.openshift.io/v1
          - kind: Secret
            version: v1
          - kind: PersistentVolumeClaim
            version: v1
          - kind: ServiceAccount
            version: v1
          - kind: Role
            version: authorization.openshift.io/v1
          - kind: RoleBinding
            version: authorization.openshift.io/v1
          - kind: Service
            version: v1
          - kind: Route
            version: route.openshift.io/v1
        specDescriptors:
          - description: Environment of PAM to deploy.
            displayName: Environment
            path: environment
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:label"
          - description: PAM version to be installed.
            displayName: Version
            path: commonConfig.version
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:label"
        statusDescriptors:
          - description: Deployments for the KieApp environment.
            displayName: Deployments
            path: deployments
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podStatuses"
          - description: The address for accessing workbench, if it is deployed.
            displayName: Workbench URL
            path: consoleHost
            x-descriptors:
              - "urn:alm:descriptor:org.w3:link"
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: kie-cloud-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - "*"
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - serviceaccounts
              verbs:
                - "*"
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - "*"
            - apiGroups:
                - app.kiegroup.org
                - apps.openshift.io
                - image.openshift.io
                - build.openshift.io
                - route.openshift.io
              resources:
                - "*"
              verbs:
                - "*"
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
                - rolebindings
              verbs:
                - "*"
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
      deployments:
        - name: kie-cloud-operator
          spec:
            replicas: 1
            strategy:
              type: Recreate
            selector:
              matchLabels:
                name: kie-cloud-operator
            template:
              metadata:
                labels:
                  name: kie-cloud-operator
              spec:
                serviceAccountName: kie-cloud-operator
                containers:
                  - name: kie-cloud-operator
                    image: quay.io/kiegroup/kie-cloud-operator:0.1
                    ports:
                      - containerPort: 60000
                        name: metrics
                    command:
                      - kie-cloud-operator
                    imagePullPolicy: Always
                    readinessProbe:
                      exec:
                        command:
                          - stat
                          - /tmp/operator-sdk-ready
                      initialDelaySeconds: 4
                      periodSeconds: 10
                      failureThreshold: 1
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "kie-cloud-operator"
